name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '24.2.0'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies with fallback
      run: |
        npm config set registry https://registry.npmjs.org
        n=0
        until [ "$n" -ge 2 ]
        do
          npm install -g @11ty/eleventy --no-audit --prefer-offline && break
          n=$((n+1))
          sleep 5
          npm config set registry https://registry.npmmirror.com  # Fallback mirror
        done
        npm install markdown-it markdown-it-front-matter fs-extra --no-audit --prefer-offline
    
    - name: Build site
      run: |
        mkdir -p _site
        cp -r css js images _site/
        node .github/scripts/build.js
    
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./_site/
        server-dir: ${{ secrets.FTP_SERVER_DIR }}/